version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.3

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
    SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - echo "------setup-env------"
        - validate:
            type: script
            script:
              - echo "------validate------"
        - setup-app:
            type: script
            script:
               - echo "------setup-app------"
        - test:
            type: script
            script:
              - ./vendor/bin/drush runserver 8080 &
              - ./vendor/bin/phpunit -c docroot/core docroot/core --group=ban || true
        - build-artifact:
            type: script
            script:
              - mkdir /tmp/acli-push-artifact

  post-deploy:
    steps:
      - deploy:
          script:
            - echo "------post-deploy------"

  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy

  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
