version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.3

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
    SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
