version: 1.0.0
services:
  - php:
     version: 8.2

ssh-keys:
  DECRYPTABLE_SSH_KEY:
    secure: 2acIshWAndTh1sG0esOn

variables:
  COMPOSER_BIN: $SOURCE_DIR/vendor/bin
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
  TEST_VAR: {"x":5,"y":6}
  API_KEY: "${decrypt:api_key}"
  API_SECRET: "${decrypt:api_secret}"
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    API_KEY: 
      secure: "skjdhcfoiwejdlwekjfierjfejkfkjefojoe"
    API_SECRET: 
      secure: "sdfjsdlfjsldkfjlsdkjflsdkjfslkdjfslkdjfslkdjf"

cde-databases:
  - drupal

events:
  build:
    steps:
      - composer_setup:
          type: script
          script:
            - sleep 10
            - echo $TEST_VAR
            - echo $PIPELINE_WEBHOOK_EVENT
            - echo $SOURCE_VCS_PATH
      - branch_check:
          type: script
          script:
            - echo "Creating test script file in repository..."
            - |
              cat > $SOURCE_DIR/branch-check.sh << 'SCRIPT_EOF'
              #!/bin/bash
              set -e
              
              echo "=== Branch Check Script ==="
              echo "Current branch: $SOURCE_VCS_PATH"
              echo "Git commit: $PIPELINE_GIT_HEAD_REF"
              echo "Pipeline event: $PIPELINES_CURRENT_EVENT"
              echo "Test variable: $TEST_VAR"
              
              # Check if running on master
              if [ "$SOURCE_VCS_PATH" = "master" ]; then
                echo "✓ Running on master branch"
                echo "Deploying to production environment..."
                export DEPLOY_ENV="production"
              elif [ "$SOURCE_VCS_PATH" = "develop" ]; then
                echo "✓ Running on develop branch"
                echo "Deploying to staging environment..."
                export DEPLOY_ENV="staging"
              else
                echo "✓ Running on feature branch: $SOURCE_VCS_PATH"
                echo "Deploying to dev environment..."
                export DEPLOY_ENV="dev"
              fi
              
              echo "Target environment: $DEPLOY_ENV"
              
              # Write result to a file
              echo "Branch: $SOURCE_VCS_PATH" > $SOURCE_DIR/deployment-info.txt
              echo "Environment: $DEPLOY_ENV" >> $SOURCE_DIR/deployment-info.txt
              echo "Commit: $PIPELINE_GIT_HEAD_REF" >> $SOURCE_DIR/deployment-info.txt
              SCRIPT_EOF
            - chmod +x $SOURCE_DIR/branch-check.sh
            - echo "✓ Script created successfully"
            - ls -lh $SOURCE_DIR/branch-check.sh
            - $SOURCE_DIR/branch-check.sh
      
  post-deploy:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - sleep 50
      - sync_databases:
          type: script
          script:
            - echo "Database sync completed"
