version: 1.0.0
services:
  - php:
     version: 8.2

ssh-keys:
  DECRYPTABLE_SSH_KEY:
    secure: 2acIshWAndTh1sG0esOn

variables:
  COMPOSER_BIN: $SOURCE_DIR/vendor/bin
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
  TEST_VAR: {"x":5,"y":6}
  API_KEY: "${decrypt:api_key}"
  API_SECRET: "${decrypt:api_secret}"
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    API_KEY: 
      secure: "skjdhcfoiwejdlwekjfierjfejkfkjefojoe"
    API_SECRET: 
      secure: "sdfjsdlfjsldkfjlsdkjflsdkjfslkdjfslkdjfslkdjf"

cde-databases:
  - drupal

events:
  build:
    steps:
      - composer_setup:
          type: script
          script:
            - sleep 10
            - echo $TEST_VAR
            - echo $PIPELINE_WEBHOOK_EVENT
            - echo $SOURCE_VCS_PATH
  post-deploy:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - sleep 50
      - sync_databases:
          type: script
          script:
            - echo "Database sync completed"
